namespace ControlWorkbench.Protocol.Protocols.MAVLink;

/// <summary>
/// MAVLink protocol constants and definitions.
/// Compatible with MAVLink 2.0 specification.
/// </summary>
public static class MAVLinkConstants
{
    public const byte STX_V1 = 0xFE;
    public const byte STX_V2 = 0xFD;
    public const int HEADER_LEN_V1 = 6;
    public const int HEADER_LEN_V2 = 10;
    public const int CHECKSUM_LEN = 2;
    public const int SIGNATURE_LEN = 13;
    public const int MAX_PAYLOAD_LEN = 255;
}

/// <summary>
/// MAVLink message header structure.
/// </summary>
public class MAVLinkHeader
{
    public byte Magic { get; set; }
    public byte Length { get; set; }
    public byte IncompatFlags { get; set; }
    public byte CompatFlags { get; set; }
    public byte Sequence { get; set; }
    public byte SystemId { get; set; }
    public byte ComponentId { get; set; }
    public uint MessageId { get; set; }
}

/// <summary>
/// Common MAVLink message types used in drone/robotics applications.
/// </summary>
public enum MAVLinkMessageId : uint
{
    Heartbeat = 0,
    SysStatus = 1,
    SystemTime = 2,
    Ping = 4,
    ChangeOperatorControl = 5,
    ChangeOperatorControlAck = 6,
    AuthKey = 7,
    SetMode = 11,
    ParamRequestRead = 20,
    ParamRequestList = 21,
    ParamValue = 22,
    ParamSet = 23,
    GpsRawInt = 24,
    GpsStatus = 25,
    ScaledImu = 26,
    RawImu = 27,
    RawPressure = 28,
    ScaledPressure = 29,
    Attitude = 30,
    AttitudeQuaternion = 31,
    LocalPositionNed = 32,
    GlobalPositionInt = 33,
    RcChannelsScaled = 34,
    RcChannelsRaw = 35,
    ServoOutputRaw = 36,
    MissionRequestPartialList = 37,
    MissionWritePartialList = 38,
    MissionItem = 39,
    MissionRequest = 40,
    MissionSetCurrent = 41,
    MissionCurrent = 42,
    MissionRequestList = 43,
    MissionCount = 44,
    MissionClearAll = 45,
    MissionItemReached = 46,
    MissionAck = 47,
    SetGpsGlobalOrigin = 48,
    GpsGlobalOrigin = 49,
    ParamMapRc = 50,
    MissionRequestInt = 51,
    SafetySetAllowedArea = 54,
    SafetyAllowedArea = 55,
    AttitudeQuaternionCov = 61,
    NavControllerOutput = 62,
    GlobalPositionIntCov = 63,
    LocalPositionNedCov = 64,
    RcChannels = 65,
    RequestDataStream = 66,
    DataStream = 67,
    ManualControl = 69,
    RcChannelsOverride = 70,
    MissionItemInt = 73,
    VfrHud = 74,
    CommandInt = 75,
    CommandLong = 76,
    CommandAck = 77,
    ManualSetpoint = 81,
    SetAttitudeTarget = 82,
    AttitudeTarget = 83,
    SetPositionTargetLocalNed = 84,
    PositionTargetLocalNed = 85,
    SetPositionTargetGlobalInt = 86,
    PositionTargetGlobalInt = 87,
    LocalPositionNedSystemGlobalOffset = 89,
    HilState = 90,
    HilControls = 91,
    HilRcInputsRaw = 92,
    HilActuatorControls = 93,
    OpticalFlow = 100,
    GlobalVisionPositionEstimate = 101,
    VisionPositionEstimate = 102,
    VisionSpeedEstimate = 103,
    ViconPositionEstimate = 104,
    HighresImu = 105,
    OpticalFlowRad = 106,
    HilSensor = 107,
    SimState = 108,
    RadioStatus = 109,
    FileTransferProtocol = 110,
    Timesync = 111,
    CameraTrigger = 112,
    HilGps = 113,
    HilOpticalFlow = 114,
    HilStateQuaternion = 115,
    ScaledImu2 = 116,
    LogRequestList = 117,
    LogEntry = 118,
    LogRequestData = 119,
    LogData = 120,
    LogErase = 121,
    LogRequestEnd = 122,
    GpsInjectData = 123,
    Gps2Raw = 124,
    PowerStatus = 125,
    SerialControl = 126,
    GpsRtk = 127,
    Gps2Rtk = 128,
    ScaledImu3 = 129,
    DataTransmissionHandshake = 130,
    EncapsulatedData = 131,
    DistanceSensor = 132,
    TerrainRequest = 133,
    TerrainData = 134,
    TerrainCheck = 135,
    TerrainReport = 136,
    ScaledPressure2 = 137,
    AttPosMocap = 138,
    SetActuatorControlTarget = 139,
    ActuatorControlTarget = 140,
    Altitude = 141,
    ResourceRequest = 142,
    ScaledPressure3 = 143,
    FollowTarget = 144,
    ControlSystemState = 146,
    BatteryStatus = 147,
    AutopilotVersion = 148,
    LandingTarget = 149,
    EstimatorStatus = 230,
    WindCov = 231,
    GpsInput = 232,
    GpsRtcmData = 233,
    HighLatency = 234,
    HighLatency2 = 235,
    Vibration = 241,
    HomePosition = 242,
    SetHomePosition = 243,
    MessageInterval = 244,
    ExtendedSysState = 245,
    AdsbVehicle = 246,
    Collision = 247,
    V2Extension = 248,
    MemoryVect = 249,
    DebugVect = 250,
    NamedValueFloat = 251,
    NamedValueInt = 252,
    Statustext = 253,
    Debug = 254,
    SetupSigning = 256,
    ButtonChange = 257,
    PlayTune = 258,
    CameraInformation = 259,
    CameraSettings = 260,
    StorageInformation = 261,
    CameraCaptureStatus = 262,
    CameraImageCaptured = 263,
    FlightInformation = 264,
    MountOrientation = 265,
    LoggingData = 266,
    LoggingDataAcked = 267,
    LoggingAck = 268,
    VideoStreamInformation = 269,
    VideoStreamStatus = 270,
    WifiConfigAp = 299,
    ProtocolVersion = 300,
    AisVessel = 301,
    UavcanNodeStatus = 310,
    UavcanNodeInfo = 311,
    ParamExtRequestRead = 320,
    ParamExtRequestList = 321,
    ParamExtValue = 322,
    ParamExtSet = 323,
    ParamExtAck = 324,
    ObstacleDistance = 330,
    Odometry = 331,
    TrajectoryRepresentationWaypoints = 332,
    TrajectoryRepresentationBezier = 333,
    CellularStatus = 334,
    IsbdLinkStatus = 335,
    CellularConfig = 336,
    RawRpm = 339,
    UtmGlobalPosition = 340,
    DebugFloatArray = 350,
    OrbitExecutionStatus = 360,
    SmartBatteryInfo = 370,
    GeneratorStatus = 373,
    ActuatorOutputStatus = 375,
    TimeEstimateToTarget = 380,
    Tunnel = 385,
    OnboardComputerStatus = 390,
    ComponentInformation = 395,
    PlayTuneV2 = 400,
    SupportedTunes = 401,
    Event = 410,
    CurrentEventSequence = 411,
    RequestEvent = 412,
    ResponseEventError = 413,
    WheelDistance = 9000,
    WinchStatus = 9005,
    OpenDroneIdBasicId = 12900,
    OpenDroneIdLocation = 12901,
    OpenDroneIdAuthentication = 12902,
    OpenDroneIdSelfId = 12903,
    OpenDroneIdSystem = 12904,
    OpenDroneIdOperatorId = 12905,
    OpenDroneIdMessagePack = 12915,
    OpenDroneIdArmStatus = 12918,
    OpenDroneIdSystemUpdate = 12919,
    HygrometerSensor = 12920
}

/// <summary>
/// MAVLink autopilot types.
/// </summary>
public enum MAVAutopilot : byte
{
    Generic = 0,
    Reserved = 1,
    Slugs = 2,
    ArduPilotMega = 3,
    OpenPilot = 4,
    GenericWaypointsOnly = 5,
    GenericWaypointsAndSimpleNavigationOnly = 6,
    GenericMissionFull = 7,
    Invalid = 8,
    Ppz = 9,
    Udb = 10,
    Fp = 11,
    Px4 = 12,
    Smaccmpilot = 13,
    Autoquad = 14,
    Armazila = 15,
    Aerob = 16,
    Asluav = 17,
    SmartAp = 18,
    AirRails = 19,
    Reflex = 20
}

/// <summary>
/// MAVLink vehicle types.
/// </summary>
public enum MAVType : byte
{
    Generic = 0,
    FixedWing = 1,
    Quadrotor = 2,
    Coaxial = 3,
    Helicopter = 4,
    AntennaTracker = 5,
    Gcs = 6,
    Airship = 7,
    FreeBalloon = 8,
    Rocket = 9,
    GroundRover = 10,
    SurfaceBoat = 11,
    Submarine = 12,
    Hexarotor = 13,
    Octorotor = 14,
    Tricopter = 15,
    FlappingWing = 16,
    Kite = 17,
    OnboardController = 18,
    VtolDuorotor = 19,
    VtolQuadrotor = 20,
    VtolTiltrotor = 21,
    VtolReserved2 = 22,
    VtolReserved3 = 23,
    VtolReserved4 = 24,
    VtolReserved5 = 25,
    Gimbal = 26,
    Adsb = 27,
    Parafoil = 28,
    Dodecarotor = 29,
    Camera = 30,
    ChargingStation = 31,
    Flarm = 32,
    Servo = 33,
    Odid = 34,
    Decarotor = 35,
    Battery = 36,
    Parachute = 37,
    Log = 38,
    Osd = 39,
    ImuUnit = 40,
    GpsUnit = 41,
    WinchUnit = 42
}

/// <summary>
/// MAVLink flight modes.
/// </summary>
public enum MAVMode : byte
{
    Preflight = 0,
    Manual = 64,
    Test = 66,
    Stabilize = 80,
    Guided = 88,
    Auto = 92,
    Rtl = 93
}

/// <summary>
/// MAVLink component IDs.
/// </summary>
public enum MAVComponent : byte
{
    All = 0,
    Autopilot1 = 1,
    Camera = 100,
    Camera2 = 101,
    Camera3 = 102,
    Camera4 = 103,
    Camera5 = 104,
    Camera6 = 105,
    Servo1 = 140,
    Servo2 = 141,
    Servo3 = 142,
    Servo4 = 143,
    Servo5 = 144,
    Servo6 = 145,
    Servo7 = 146,
    Servo8 = 147,
    Servo9 = 148,
    Servo10 = 149,
    Servo11 = 150,
    Servo12 = 151,
    Servo13 = 152,
    Servo14 = 153,
    Gimbal = 154,
    Log = 155,
    Adsb = 156,
    Osd = 157,
    Peripheral = 158,
    QxCamera = 159,
    FlarmCollisionAlert = 160,
    Parachute = 161,
    Winch = 169,
    Gimbal2 = 171,
    Gimbal3 = 172,
    Gimbal4 = 173,
    Gimbal5 = 174,
    Gimbal6 = 175,
    Battery = 180,
    Battery2 = 181,
    MavlinkFtpAdapter = 190,
    Uavcan = 200,
    ImuUnit = 200,
    ImuUnit2 = 201,
    ImuUnit3 = 202,
    GpsUnit = 220,
    GpsUnit2 = 221,
    OdidTxrx = 236,
    OdidTxrx2 = 237,
    OdidTxrx3 = 238,
    UdpBridge = 240,
    UartBridge = 241,
    TunnelNode = 242,
    SystemControl = 250
}
